### ISSUE TITLE
Allow multiple Filters in: `Module::getMethodFilter()`

### ISSUE THREAD

**Issue by sweisgerber-dev** [Project-ARTist/ARTist#17]
Allow multiple Filters in: `Module::getMethodFilter()`

Preferably Multiple Black- and WhiteListFilter.

BlackList Filter should have precedence over WhiteList filter, to be able to exclude single classes or methods, when you whitelist a whole package-namespace.

### Files:

- Interface: `compiler/optimizing/artist/modules/module.h`
    - and it's implementations
- Usage: `compiler/optimizing/optimizing_compiler.cc`

**Comment by sweisgerber-dev** [comment]
Implementation is done:
- https://github.com/Project-ARTist/ARTist/commit/820b61cd2f08f97c54a75ad517395557debab7c9
- https://github.com/Project-ARTist/art/commit/348b87af5013cdd1d8588ce34ea03d4c1bc2e5b1

Need TestDevice

**Comment by schrnz** [comment]
Tbh the interface is already generic enough and this change would make it more specific imo. Instead of two, there could be any number of filters. However, this can easily be implemented by creating a new filter that instantiates multiple sub-filters, applies them in any order desired by the developer and combines their results.

The implementations of the functionality you wanted to have, i.e. combinations of whitelisting and blacklisting, are straightforward in this approach.

Example: Whitelist with a blacklist of exceptions (pseudo-code): 
```
WhitelistFilter whitelist([sig1, sig2, ...]);
BlacklistFilter exceptions([sig1, sig4, ...]);
return whitelist.accept(method_sig) && !exceptions.accept(method_sig);
```

I would argue that this solution is more generic since you could implement any combination of two or more filters, so the new changes are not extending the expressiveness of the API but might introduce problems if there are less than two filters and may confuse people b/c it is not immediately clear why two filters seem to be expected. 

Of course we can discuss this, but my current stance is that the API should be as generic as possible to cover a wide range of use cases, and the proposed changes feel a bit like tailoring the API towards a specific module. 

I would like to hear your opinion on this @sweisgerber-dev .

**Comment by sweisgerber-dev** [comment]
My change doesn't make the creation of two filters necessary (set one or both null), but creating a new FilterType is indeed much more elegant.

I'll apply your proposal.

**Comment by sweisgerber-dev** [comment]
Implemented in:

- Project-ARTist/art/pull/8 (no changes)
- Project-ARTist/ARTist/pull/18
